
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getaccount", targetNamespace = "http://ws/", className = "proxy.Getaccount")
    @ResponseWrapper(localName = "getaccountResponse", targetNamespace = "http://ws/", className = "proxy.GetaccountResponse")
    @Action(input = "http://ws/BankService/getaccountRequest", output = "http://ws/BankService/getaccountResponse")
    public Account getaccount(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "accountList", targetNamespace = "http://ws/", className = "proxy.AccountList")
    @ResponseWrapper(localName = "accountListResponse", targetNamespace = "http://ws/", className = "proxy.AccountListResponse")
    @Action(input = "http://ws/BankService/accountListRequest", output = "http://ws/BankService/accountListResponse")
    public List<Account> accountList();

    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Conversion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Conversion", targetNamespace = "http://ws/", className = "proxy.Conversion")
    @ResponseWrapper(localName = "ConversionResponse", targetNamespace = "http://ws/", className = "proxy.ConversionResponse")
    @Action(input = "http://ws/BankService/ConversionRequest", output = "http://ws/BankService/ConversionResponse")
    public double conversion(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

}
